import { Header } from "@/components/Header";
import { SectionLabel } from "@/components/editorial";
import { ArtistPersona } from "@/components/future/artist-persona/ArtistPersona";
import { NextModuleCta } from "@/components/NextModuleCta";

export default function ArtistPersonaPage() {
  return (
    <div className="ptta-root min-h-screen bg-page text-ink flex flex-col">
      <Header showBack backHref="/demo-hub" />
      <main className="flex-1 px-5 py-8 w-full max-w-[560px] md:max-w-[780px] lg:max-w-[880px] mx-auto">
        <SectionLabel label="Artist Persona" tag="Module" />
        <div className="flex items-baseline justify-between mt-2 mb-2">
          <h1
            className="font-serif text-4xl md:text-5xl lg:text-6xl leading-[0.98]"
            style={{ letterSpacing: "-0.01em" }}
          >
            Talk to the painter.
          </h1>
        </div>
        <p className="text-body-fg text-base md:text-lg mb-8 max-w-[620px]">
          Pick a painter from our collection and ask them anything — about a brushstroke, a memory, a dream.
        </p>

        <ArtistPersona />

        <p
          role="note"
          className="mt-6 text-xs md:text-sm text-muted-fg italic leading-snug max-w-[620px]"
        >
          Responses are generated by AI based on publicly available information about each artist. They may contain inaccuracies — treat them as creative interpretation, not historical fact.
        </p>

        <div className="mt-10">
          <NextModuleCta fromSlug="artist-persona" />
        </div>
      </main>
    </div>
  );
}
